name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1 hidden
      id: test-1-hidden
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1 hidden
        setup-command: ''
        command: python3 project_3_1/dlog.py
        input: |-
          13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084171
          11717829880366207009516117596335367088558084999998952205599979459063929499736583746670572176471460312928594829675428279466566527115212748467589894601965568
          9005975822737067404236566970662208696004503525363577365858600116297323240022401972074293360970474148065482214753848249657128498670355080686792296735580550
        expected-output: '606358051111'
        comparison-method: contains
        timeout: 2
        max-score: 49
    - name: Test 1 provided
      id: test-1-provided
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1 provided
        setup-command: ''
        command: python3 project_3_1/dlog.py
        input: |-
          13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084171
          11717829880366207009516117596335367088558084999998952205599979459063929499736583746670572176471460312928594829675428279466566527115212748467589894601965568
          3239475104050450443565264378728065788649097520952449527834792452971981976143292558073856937958553180532878928001494706097394108577585732452307673444020333
        expected-output: '375374217830'
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 2
        setup-command: cd project_3_2; nohup python3 rsa_signing_server.py 49104 &;
          nohup python3 rsa_verify_server.py 49105 &;
        command: python3 sign.py < input.txt
        timeout: 2
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1-HIDDEN_RESULTS: "${{steps.test-1-hidden.outputs.result}}"
        TEST-1-PROVIDED_RESULTS: "${{steps.test-1-provided.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
      with:
        runners: test-1-hidden,test-1-provided,test-2
